# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0befc5fd150deafb19c190c6a5e43f19c012c87e99c7ff88a7a149a58805ad2ea0a1c4d45e3287e9ee40432a29fe58d8d9c56bde8dbefdf3f3259bdae2228232

test:
  secret_key_base: 989934177e520cc3aea7d2596d13e460454ceaa78511ae19d572e04ff59e4beaf9544d1159238089bf72db766e5993d338ab3d149a9a21bda634789b45b50d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
